### ISSUE TITLE
Still have a memory leak

### ISSUE THREAD

**Issue by lolerfox** [Jarsa132/deskthing-volctrl#1]
for some reason, even though the changelog 1.1.3 says that the memory leak has been fixed... It's still happening

![2024-11-02 173909](https://github.com/user-attachments/assets/8292c8d6-22e2-4c5a-8e03-1865a67b3194)

Some information:
Operating system: Windows 10 Pro x64 22H2.
Installed DeskThing WebApp:
![изображение](https://github.com/user-attachments/assets/be1bdb05-a54d-4b4f-8a85-195e8dc6f7a4)

**Comment by Jarsa132** [comment]
Fixed in [v1.1.4](https://github.com/Jarsa132/deskthing-volctrl/releases/tag/v1.1.4)
